name: bibisco # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: I'm just packaging the open source bibisco tool for writers as a snap
description: |
  I wanted to try packaging, I know how to rpm and deb, so this will be new and interesting, I hope

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  my-part:
    # See 'snapcraft plugins'
    plugin: nil
